name: Modules PR Workflow

on:
  pull_request:
    paths:
      - modules/**

permissions:
  pull-requests: write
  contents: write

jobs:
  workflow-setup:
    name: Setup workflow
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-modules.outputs.matrix }}
      changed_modules: ${{ steps.changed-modules.outputs.paths }}
      changed_modules_spaces: ${{ steps.changed-modules.outputs.changed_modules_spaces }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files_ignore: '**/CHANGELOG.md'
      - name: Get changed modules
        id: changed-modules
        run: |
          ## CHANGED_FILES
          ## ex: '/modules/k8s_app/main.tf /modules/gke_cluster/main.tf'
          CHANGED_FILES="${{ steps.changed-files.outputs.all_modified_files }}"
          ## CHANGED_MODULES
          ## ex: '/modules/k8s_app,/modules/gke_cluster'
          CHANGED_MODULES=$(for i in $CHANGED_FILES; do echo $i | grep modules | cut -d / -f 1-2 ; done | sort -u | paste -s -d, -)
          ## MATRIX
          ## ex: ["modules/k8s_app","modules/gke_cluster"]
          MATRIX=$(echo $CHANGED_MODULES | sed -s 's/^/["/g' | sed -s 's/,/","/g' | sed -s 's/$/"]/g')
          CHANGED_MODULES_SPACES=$(echo $CHANGED_MODULES | sed -s 's/,/ /g')
          echo "::set-output name=paths::$CHANGED_MODULES"
          echo "::set-output name=changed_modules_spaces::$CHANGED_MODULES_SPACES"
          echo "::set-output name=matrix::{\"module\":$MATRIX}"

  update-readme:
    name: Update README for changed modules
    runs-on: ubuntu-latest
    needs: workflow-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: ${{ needs.workflow-setup.outputs.changed_modules }}
          output-file: README.md
          output-method: inject
          git-push: "true"

  module-workflow:
    name: Individual module workflow
    runs-on: ubuntu-latest
    needs: workflow-setup
    strategy:
      matrix: ${{fromJson(needs.workflow-setup.outputs.matrix)}}
    defaults:
      run:
        working-directory: ${{ matrix.module }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
